### ISSUE TITLE
迅雷离线不能用了，希望能够抽空更新一下，万分感谢！

### ISSUE THREAD

**Issue by lonsx** [ytan-git/plugin.video.myclouds#1]
迅雷离线不能用了，希望能够抽空更新一下，万分感谢！
错误信息：
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\myclouds.py", line 612, in <module>
                                                do_add_account(cloudname)
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\myclouds.py", line 218, in do_add_account
                                                r = do_login_cloud_password(cloud, username, password)
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\myclouds.py", line 158, in do_login_cloud_password
                                                result = cloud.login(user, passwd)
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\lib\Clouds\CloudXunlei\CloudXunlei.py", line 51, in login
                                                vfcode = self.getvfcode('http://verify.xunlei.com/image?cachetime=')
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\lib\Clouds\CloudXunlei\CloudXunlei.py", line 231, in getvfcode
                                                cdg.doModal()
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\lib\Clouds\CloudXunlei\captcha.py", line 201, in doModal
                                                default=self.inputString, url=self.url)
                                              File "E:\KodiPortable\App\Kodi\portable_data\addons\plugin.video.myclouds-master\lib\Clouds\CloudXunlei\captcha.py", line 39, in __init__
                                                self.captcha, self.verify_key = self.initializeImage()
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--`

**Comment by lonsx** [comment]
已查明是由于resources下images文件夹未建立导致的，手动建立一个images文件夹后修复。
谢谢！
